// Database access layer: one tiny `Db` interface over two Postgres engines.
//   - postgres.js → Supabase Postgres (production, via the connection pooler)
//   - PGlite      → in-process Postgres (local dev without Supabase, tests)
// Domain code writes plain Postgres SQL with $1, $2… placeholders.
import postgres from 'postgres'
import type { PGlite, Transaction as PgliteTransaction } from '@electric-sql/pglite'
import { appTimezone } from './env'

export type Row = Record<string, unknown>

export interface Db {
  /**
   * Parametrised query ($1, $2…). Returns plain row objects.
   * JSONB parameters: pass JSON.stringify(value) and cast `$n::text::jsonb` —
   * a bare `$n::jsonb` makes postgres.js stringify the string a second time.
   */
  query<T extends Row = Row>(text: string, params?: unknown[]): Promise<T[]>
  /** Runs several statements without parameters (DDL). */
  exec(text: string): Promise<void>
  /**
   * Runs `fn` inside one transaction (commit on success, rollback on throw).
   * Inside `fn` use ONLY the `tx` argument — PGlite has a single connection,
   * so a query on the outer Db would wait for the transaction forever.
   * Calling transaction() on a tx just runs `fn` in the same transaction.
   */
  transaction<T>(fn: (tx: Db) => Promise<T>): Promise<T>
}

// ---------------------------------------------------------------- postgres.js

function sanitisePostgresUrl(raw: string): string {
  // Vercel/Supabase URLs carry params such as ?sslmode=require&supa=base-pooler.x;
  // postgres.js would forward unknown ones as startup parameters. SSL is set below.
  const url = new URL(raw)
  url.search = ''
  return url.toString()
}

function isLocalHost(raw: string): boolean {
  const host = new URL(raw).hostname
  return host === 'localhost' || host === '127.0.0.1' || host === '::1'
}

type PgClient = postgres.Sql | postgres.TransactionSql

function wrapPostgres(sql: PgClient, inTransaction: boolean): Db {
  const db: Db = {
    async query<T extends Row = Row>(text: string, params: unknown[] = []) {
      const rows = await sql.unsafe(text, params as postgres.ParameterOrJSON<never>[])
      return Array.from(rows) as unknown as T[]
    },
    async exec(text: string) {
      await sql.unsafe(text)
    },
    async transaction<T>(fn: (tx: Db) => Promise<T>): Promise<T> {
      if (inTransaction) return fn(db)
      const result = await (sql as postgres.Sql).begin((tx) => fn(wrapPostgres(tx, true)))
      return result as T
    },
  }
  return db
}

export function createPostgresDb(url: string): Db {
  const sql = postgres(sanitisePostgresUrl(url), {
    // Supabase's transaction pooler (port 6543) does not support prepared statements.
    prepare: false,
    max: 5,
    idle_timeout: 20,
    connect_timeout: 10,
    ssl: isLocalHost(url) ? false : 'require',
    onnotice: () => {},
  })
  return wrapPostgres(sql, false)
}

// --------------------------------------------------------------------- PGlite

type PgliteClient = PGlite | PgliteTransaction

function wrapPglite(pg: PgliteClient, inTransaction: boolean): Db {
  const db: Db = {
    async query<T extends Row = Row>(text: string, params: unknown[] = []) {
      const result = await pg.query<T>(text, params)
      return result.rows
    },
    async exec(text: string) {
      await pg.exec(text)
    },
    async transaction<T>(fn: (tx: Db) => Promise<T>): Promise<T> {
      if (inTransaction) return fn(db)
      return (pg as PGlite).transaction((tx) => fn(wrapPglite(tx, true)))
    },
  }
  return db
}

/** dataDir null → in-memory database (tests, ephemeral serverless fallback). */
export async function createPgliteDb(dataDir: string | null): Promise<Db> {
  const { PGlite } = await import('@electric-sql/pglite')
  if (dataDir) {
    const { mkdirSync } = await import('node:fs')
    mkdirSync(dataDir, { recursive: true })
  }
  const pg = dataDir ? new PGlite(dataDir) : new PGlite()
  await pg.waitReady
  return wrapPglite(pg, false)
}

// --------------------------------------------------------------------- schema

/**
 * Idempotent schema. Timestamps are timestamptz (dashboards can aggregate them);
 * SELECTs format them with tsText() into the 'YYYY-MM-DD HH:MM:SS' strings the
 * UI expects. RLS is enabled with no policies: the public Supabase key cannot
 * read anything through PostgREST, while the server connects as the table
 * owner and enforces roles in route handlers.
 */
export const SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS items (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name     TEXT NOT NULL UNIQUE,
  quantity INTEGER NOT NULL,
  minimum  INTEGER NOT NULL DEFAULT 0,
  unit     TEXT NOT NULL DEFAULT 'szt',
  location TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS audit_log (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts         TIMESTAMPTZ NOT NULL DEFAULT now(),
  actor      TEXT NOT NULL DEFAULT 'magazynier',
  actor_id   UUID NULL,
  text       TEXT NOT NULL,
  item_id    INTEGER NULL,
  item_name  TEXT NOT NULL,
  delta      INTEGER NOT NULL DEFAULT 0,
  before     INTEGER NOT NULL DEFAULT 0,
  after      INTEGER NOT NULL DEFAULT 0,
  event_type TEXT NOT NULL DEFAULT 'stock_change',
  details    TEXT NOT NULL DEFAULT '',
  undo_of    INTEGER NULL,
  undone_by  INTEGER NULL
);

CREATE TABLE IF NOT EXISTS reorder_drafts (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id    INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  item_name  TEXT NOT NULL,
  quantity   INTEGER NOT NULL,
  unit       TEXT NOT NULL,
  deliver_on DATE NOT NULL,
  status     TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  decided_by TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS one_pending_reorder_per_item
  ON reorder_drafts(item_id) WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS zones (
  id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    TEXT NOT NULL UNIQUE,
  created TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Rzeczywisty rzut hali: ścieżki nagrane telefonem (PDR, metry od startu).
CREATE TABLE IF NOT EXISTS map_paths (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  points      JSONB NOT NULL,
  markers     JSONB NOT NULL DEFAULT '[]'::jsonb,
  step_length REAL NOT NULL DEFAULT 0.7,
  actor       TEXT NOT NULL DEFAULT 'magazynier',
  created     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS procedures (
  id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic   TEXT NOT NULL UNIQUE,
  text    TEXT NOT NULL,
  created TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Unconfirmed change cards (confirm-before-write). Serverless instances share them here.
CREATE TABLE IF NOT EXISTS proposals (
  id         TEXT PRIMARY KEY,
  payload    JSONB NOT NULL,
  created_by UUID NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Parsed import files waiting for mapping confirmation.
CREATE TABLE IF NOT EXISTS pending_imports (
  id         TEXT PRIMARY KEY,
  headers    JSONB NOT NULL,
  data_rows  JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS settings (
  key        TEXT PRIMARY KEY,
  value      JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- data_version: bumped after every write; clients poll it instead of a WebSocket.
CREATE TABLE IF NOT EXISTS app_meta (
  key   TEXT PRIMARY KEY,
  value INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS profiles (
  user_id      UUID PRIMARY KEY,
  email        TEXT NOT NULL DEFAULT '',
  display_name TEXT NOT NULL DEFAULT '',
  role         TEXT NOT NULL DEFAULT 'oczekujacy' CHECK (role IN ('pracownik', 'kierownik', 'oczekujacy')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- v2: accounts waiting for approval (databases created by v1 have the old check).
ALTER TABLE profiles ALTER COLUMN role SET DEFAULT 'oczekujacy';
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE profiles ADD CONSTRAINT profiles_role_check CHECK (role IN ('pracownik', 'kierownik', 'oczekujacy'));

-- v2: per-user request budgets for the paid AI endpoints.
CREATE TABLE IF NOT EXISTS rate_limits (
  key          TEXT PRIMARY KEY,
  window_start TIMESTAMPTZ NOT NULL DEFAULT now(),
  count        INTEGER NOT NULL DEFAULT 0
);

-- v2: dashboard range filters, the activity log order and per-item trends.
CREATE INDEX IF NOT EXISTS audit_log_ts_idx ON audit_log (ts DESC, id DESC);
CREATE INDEX IF NOT EXISTS audit_log_item_ts_idx ON audit_log (item_id, ts);

ALTER TABLE items ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE reorder_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE procedures ENABLE ROW LEVEL SECURITY;
ALTER TABLE proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE pending_imports ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_meta ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE map_paths ENABLE ROW LEVEL SECURITY;
`

/** Bump when SCHEMA_SQL changes so existing databases run the DDL again. */
export const SCHEMA_VERSION = 3

async function schemaIsCurrent(db: Db): Promise<boolean> {
  // to_regclass never raises, so this is safe inside a caller's transaction.
  const [table] = await db.query<{ found: boolean }>("SELECT to_regclass('app_meta') IS NOT NULL AS found")
  if (!table?.found) return false
  const rows = await db.query<{ value: number }>("SELECT value FROM app_meta WHERE key = 'schema_version'")
  return rows[0]?.value === SCHEMA_VERSION
}

/**
 * Creates tables/indexes if missing. A cold start on an up-to-date database
 * costs one SELECT; otherwise the DDL runs once, serialised by an advisory
 * lock so concurrent cold starts don't race.
 */
export async function ensureSchema(db: Db): Promise<void> {
  if (await schemaIsCurrent(db)) return
  await db.transaction(async (tx) => {
    await tx.query('SELECT pg_advisory_xact_lock(724242)')
    await tx.exec(SCHEMA_SQL)
    await tx.query(
      `INSERT INTO app_meta (key, value) VALUES ('schema_version', $1)
       ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value`,
      [SCHEMA_VERSION],
    )
  })
}

// ---------------------------------------------------------------- time helpers

/**
 * SQL expression formatting a timestamptz column as local 'YYYY-MM-DD HH:MM:SS'
 * text, e.g. `SELECT ${tsText('ts')} FROM audit_log` → column "ts".
 */
export function tsText(column: string, alias = column.split('.').pop() ?? column): string {
  if (!/^[a-z_][a-z0-9_.]*$/.test(column) || !/^[a-z_][a-z0-9_]*$/.test(alias)) {
    throw new Error(`Invalid column name: ${column}`)
  }
  return `to_char(${column} AT TIME ZONE '${appTimezone()}', 'YYYY-MM-DD HH24:MI:SS') AS ${alias}`
}

/** SQL expression formatting a DATE column as 'YYYY-MM-DD' text. */
export function dateText(column: string, alias = column.split('.').pop() ?? column): string {
  if (!/^[a-z_][a-z0-9_.]*$/.test(column) || !/^[a-z_][a-z0-9_]*$/.test(alias)) {
    throw new Error(`Invalid column name: ${column}`)
  }
  return `to_char(${column}, 'YYYY-MM-DD') AS ${alias}`
}

/** Today's date in APP_TIMEZONE as 'YYYY-MM-DD'. */
export function todayLocal(now: Date = new Date()): string {
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: appTimezone(),
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).formatToParts(now)
  const get = (type: string) => parts.find((part) => part.type === type)?.value ?? ''
  return `${get('year')}-${get('month')}-${get('day')}`
}

/** Next Tuesday strictly after `today` ('YYYY-MM-DD'), like the Python _next_tuesday. */
export function nextTuesday(today: string = todayLocal()): string {
  const [year, month, day] = today.split('-').map(Number)
  const date = new Date(Date.UTC(year, month - 1, day))
  const weekday = (date.getUTCDay() + 6) % 7 // Monday = 0, like Python's weekday()
  const daysUntil = (1 - weekday + 7) % 7 || 7
  date.setUTCDate(date.getUTCDate() + daysUntil)
  return date.toISOString().slice(0, 10)
}
